server:
  port: 8081
  servlet:
    context-path: /
spring:
  data:
    redis:
      host: localhost
      port: 30379
      password: redis

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
